name: Delight Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Executable Perms
        run: chmod +x ./gradlew

      - name: Delight Unit Tests
        run: ./gradlew test

      - name: Delight Code Review
        run: ./gradlew ktlintCheck
