name: Delight Build

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/action.yml"
jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"
